config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up:'register'  }
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  resources :portfolios, except: [:show]
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :topic
    enum status: { draft:0, published:1 }
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    validates_presence_of :title, :body
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern
  
  def self.image_generator(height: , width:)
    "http://placehold.it/#{height}x#{width}"
  end
  
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image
    
    def self.angular
        where(subtitle: "Angular")
    end
    
    scope :ruby_on_rails, -> {
        where(subtitle: "Ruby on Rails")
    }
    
    after_initialize :set_defaults
    
    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: '600', width:'400')
        self.thumb_image ||= Placeholder.image_generator(height: '350', width:'200')
    end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized
  after_initialize :set_defaults
    
  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width:'250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :blogs
    validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates_presence_of :name
  def first_name
    self.name.split.first
  end
  
  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  
  before_action :set_source
  
  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your Post is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was removed.' }
    end
  end
  
  def toggle_status 
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern
    
    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills =Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
    
    def index
       @portfolio_items = Portfolio.all
    end
    
    def angular 
        @angular_portfolio_items = Portfolio.angular
    end
    
    def show
        
    end
    
    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end
    
    def create
        @portfolio_item = Portfolio.new(portfolio_params)
        if @portfolio_item.save
            redirect_to portfolios_path, notice: 'Portfolio item created'
        else
            render :new 
        end
    end
    
    def edit
    end
    
    def update
        if @portfolio_item.update_attributes(portfolio_params)
            render @portfolio_item, notice: 'Portfolio item updated'
        else
            render :edit, alert: 'Something went wrong'
        end
    end
    
    def destroy
        @portfolio_item.destroy
        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: 'Portfolio was removed.' }
        end
    end
    
    private
    
    def portfolio_params
        params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
    end
    
    def set_portfolio
        @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path%>
    <% end %>
    <%= yield %>
    <% if session[:source]%>
      <p>Thanks for visiting me from <%= session[:source]%></p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name if current_user %></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<% @skills.each do |x| %>
<p><%= x.title %> </p> 
<p><%= x.percent_utilized%></p>
<%end%>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items</h1>

<%= link_to "Create new item", new_portfolio_url %>

<% @angular_portfolio_items.each do |item| %>
    <p><%= link_to item.title, portfolio_show_path(item) %></p>
    <p><%= item.subtitle %></p>
    <p><%= item.body %></p>
    <%=  image_tag item.thumb_image unless item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(item) %>
    <%= link_to 'Delete Portfolio Item', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title%>
    </div>
    
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>
    
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    
    <div class="actions">
        <%= f.submit %>
    </div>
<%end%>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create new item", new_portfolio_url %>

<% @portfolio_items.each do |item| %>
    <p><%= link_to item.title, portfolio_show_path(item) %></p>
    <p><%= item.subtitle %></p>
    <p><%= item.body %></p>
    <%=  image_tag item.thumb_image unless item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(item) %>
    <%= link_to 'Delete Portfolio Item', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title%>
    </div>
    
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>
    
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    
    <ul>
        <%= f.fields_for :technologies do |technology_form| %>
            <li>
                <%= technology_form.label :name %>
                <%= technology_form.text_field :name %>
            </li>
        <% end %>
    </ul>
    
    <div class="actions">
        <%= f.submit %>
    </div>
<%end%>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>
<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>

<h2>Technologies used:</h2>
<% @portfolio_item.technologies.each do |t|%>
<p>
    <%= t.name %>
</p>
<%end%>